"use client";
import {useState} from 'react';import Link from 'next/link';
import type {DiscoverUserItem,FriendStatus} from '@/app/actions/discover';
import UserCard from './UserCard';import styles from './Discover.module.css';
type Tab='suggested'|'community'|'requests';
export default function DiscoverClient({initialUsers}:{initialUsers:DiscoverUserItem[]}){
 const [users,setUsers]=useState(initialUsers);const [query,setQuery]=useState('');const [tab,setTab]=useState<Tab>('suggested');const [type,setType]=useState('');const [cursor,setCursor]=useState(0);
 const matched=users.filter(u=>u.isMatched);const requests=users.filter(u=>u.friendStatus==='PENDING_RECEIVED');const types=[...new Set(users.flatMap(u=>u.testResults.map(t=>t.resultName)))].sort();
 const pool=tab==='suggested'?matched:tab==='requests'?requests:users;const q=query.trim().toLocaleLowerCase('vi');const filtered=pool.filter(u=>(!q||[u.username,u.hobbies,u.location,...u.testResults.map(t=>t.resultName)].filter(Boolean).join(' ').toLocaleLowerCase('vi').includes(q))&&(!type||u.testResults.some(t=>t.resultName===type)));
 const index=Math.min(cursor,Math.max(0,filtered.length-1));const active=filtered[index];const rest=filtered.filter(u=>u.id!==active?.id);
 function updateStatus(id:string,status:FriendStatus){setUsers(us=>us.map(u=>u.id===id?{...u,friendStatus:status}:u));}
 function choose(next:Tab){setTab(next);setCursor(0);}
 return <div className={styles.discoverGrid}><aside className={styles.sidebar}><small>KHÔNG GIAN KẾT NỐI</small><nav aria-label="Danh mục Discover"><button aria-pressed={tab==='suggested'} onClick={()=>choose('suggested')}>Gợi ý cho bạn <span>{matched.length}</span></button><button aria-pressed={tab==='community'} onClick={()=>choose('community')}>Cộng đồng <span>{users.length}</span></button><button aria-pressed={tab==='requests'} onClick={()=>choose('requests')}>Lời mời nhận được <span>{requests.length}</span></button></nav><div className={styles.sidebarNote}><span>PERSONALITY IN PIECES.</span><h2>Bắt đầu từ một điểm chung</h2><p>Ghé thăm hồ sơ, tìm sở thích đồng điệu và gửi một lời mời kết bạn.</p><Link href="/profile">Chỉnh sửa mảnh ghép của bạn →</Link></div><Link href="/discussion" className={styles.discussionLink}>Gặp nhau qua thảo luận ↗</Link></aside>
 <div className={styles.main}><div className={styles.filters}><label className={styles.searchLabel}><span>Tìm thành viên</span><input value={query} onChange={e=>{setQuery(e.target.value);setCursor(0)}} placeholder="Tên, sở thích, quốc gia hoặc kiểu…" maxLength={100}/></label><label><span>Kiểu đã chia sẻ</span><select value={type} onChange={e=>{setType(e.target.value);setCursor(0)}}><option value="">Tất cả kiểu</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select></label>{(query||type)&&<button className={styles.clear} onClick={()=>{setQuery('');setType('');setCursor(0)}}>Xóa bộ lọc</button>}</div>
 <div className={styles.sectionHeading}><div><small>DISCOVER</small><h2>{tab==='suggested'?'Những mảnh ghép có điểm chung':tab==='requests'?'Lời mời đang chờ bạn':'Khám phá cộng đồng'}</h2></div><span aria-live="polite">{filtered.length} thành viên</span></div>
 {active?<><div className={styles.featureStage}><UserCard key={active.id} user={active} featured onStatusChange={updateStatus}/><div className={styles.pager}><button disabled={index===0} onClick={()=>setCursor(index-1)} aria-label="Hồ sơ trước">←</button><span aria-live="polite">{index+1} / {filtered.length}</span><button disabled={index>=filtered.length-1} onClick={()=>setCursor(index+1)} aria-label="Hồ sơ tiếp theo">→</button></div></div>{rest.length>0&&<section className={styles.more}><h2>Tiếp tục khám phá</h2><div className={styles.cards}>{rest.map(u=><UserCard key={u.id} user={u} onStatusChange={updateStatus}/>)}</div></section>}</>:<div className={styles.empty}><span>✧</span><h3>{query||type?'Chưa tìm thấy thành viên phù hợp':tab==='requests'?'Bạn chưa có lời mời mới':tab==='suggested'?'Chưa có gợi ý cùng kiểu':'Cộng đồng đang chờ những mảnh ghép mới'}</h3><p>{query||type?'Thử một từ khóa khác hoặc bỏ bớt bộ lọc.':tab==='suggested'?'Cập nhật kiểu trên hồ sơ hoặc khám phá những thành viên khác trong cộng đồng.':'Bạn có thể ghé diễn đàn để bắt đầu một cuộc trò chuyện.'}</p>{tab!=='community'&&<button onClick={()=>choose('community')}>Khám phá cộng đồng →</button>}<Link href="/profile">Mở hồ sơ của bạn</Link></div>}
 </div></div>;
}
