import Link from 'next/link';
import { popularKnowledge } from '@/app/actions/knowledge-search';
import styles from '@/src/components/knowledge/Knowledge.module.css';
export const dynamic='force-dynamic';
export const metadata={title:'Từ điển kiến thức | MOSAIC'};
const groups=[{name:'MBTI',caption:'16 kiểu · cách nhận thức và đưa ra quyết định',overview:'/knowledge/mbti/overview',items:['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'],href:(t:string)=>'/knowledge/mbti/'+t.toLowerCase()}, {name:'Cognitive Functions',caption:'8 chức năng · những lối tiếp nhận và xử lý thông tin',overview:'/knowledge/cognitive/overview',items:['Ni','Ne','Si','Se','Ti','Te','Fi','Fe'],href:(t:string)=>'/knowledge/cognitive/'+t.toLowerCase()},{name:'Enneagram',caption:'9 kiểu · động lực, nhu cầu và những khuôn mẫu bên trong',overview:'/knowledge/enneagram/overview',items:['1','2','3','4','5','6','7','8','9'],href:(t:string)=>'/knowledge/enneagram/type-'+t}];
export default async function Page(){const popular=await popularKnowledge();const suggestions=[{label:'INFJ',href:'/knowledge/mbti/infj',count:0},{label:'Cognitive Functions',href:'/knowledge/cognitive/overview',count:0},{label:'Enneagram',href:'/knowledge/enneagram/overview',count:0},{label:'INFP',href:'/knowledge/mbti/infp',count:0}];return <div className={styles.hub}>
<header className={styles.hero}><span>MOSAIC / KNOWLEDGE</span><h1>Từ điển những mảnh ghép</h1><p>Tra cứu khái niệm, khám phá các hệ thống và đọc sâu hơn về từng kiểu.</p><form action="/search" className={styles.search}><label className={styles.srOnly} htmlFor="wiki-query">Tìm trong Knowledge</label><input id="wiki-query" name="q" placeholder="Tìm một kiểu, chức năng hoặc khái niệm…" maxLength={100} required/><button>Tìm kiếm →</button></form></header>
<div className={styles.hubGrid}><aside className={styles.side}><small>MỤC LỤC</small>{groups.map((g,i)=><a href={'#catalog-'+i} key={g.name}>{g.name}</a>)}<Link href="/knowledge/theory">Cơ sở lý thuyết</Link><div className={styles.note}><h3>Bắt đầu từ đâu?</h3><p>Đọc tổng quan trước, rồi tra cứu từng kiểu và đối chiếu các khái niệm liên quan.</p><Link href="/knowledge/theory">Đọc hướng dẫn →</Link></div></aside><div><section className={styles.popular}><div className={styles.sectionHeading}><h2>{popular.length?'Từ khóa được tìm nhiều':'Gợi ý tra cứu'}</h2><span>{popular.length?'Từ lượt tìm của thành viên':'Khám phá thư viện'}</span></div><div className={styles.tags}>{(popular.length?popular:suggestions).map(p=><Link href={p.href} key={p.href}>{p.label}{p.count>0&&<small>{p.count} lượt</small>}</Link>)}</div>{popular.length>0&&<p className={styles.muted}>Mỗi thành viên được tính một lần cho mỗi mục trong ngày.</p>}</section>
{groups.map((g,i)=><section className={styles.catalog} id={'catalog-'+i} key={g.name}><div className={styles.sectionHeading}><div><h2>{g.name}</h2><p>{g.caption}</p></div><Link href={g.overview}>Tổng quan →</Link></div><div className={styles.entryGrid}>{g.items.map((t,index)=><Link href={g.href(t)} key={t}><small>{String(index+1).padStart(2,'0')}</small><strong>{g.name==='Enneagram'?'Type '+t:t}</strong><span>Đọc bài →</span></Link>)}</div></section>)}<section className={styles.theory}><small>NỀN TẢNG</small><h2>Hiểu cách MOSAIC diễn giải</h2><p>Cơ sở lý thuyết, nguồn tham khảo và nguyên tắc đọc các hệ thống typology.</p><Link href="/knowledge/theory">Khám phá cơ sở lý thuyết →</Link></section></div></div></div>;}
