import Link from 'next/link';
import styles from '@/src/components/settings/Settings.module.css';
export const metadata = { title:'Quyền riêng tư · MOSAIC' };
export default function PrivacyPage() {
  return <div className={styles.page}><p className={styles.eyebrow}>MOSAIC / PRIVACY</p><h1>Quyền riêng tư</h1><p className={styles.intro}>Các lựa chọn dữ liệu đang có trong MOSAIC.</p>
    <section className={styles.card}><h2>Tài khoản và hồ sơ</h2><p>Clerk quản lý đăng nhập và các thông tin tài khoản liên quan. MOSAIC lưu hồ sơ bạn cung cấp, ảnh đại diện, kết quả bài test và các dữ liệu cần thiết cho bạn bè, tin nhắn, thảo luận và thông báo. Ảnh và tệp tải lên sử dụng dịch vụ lưu trữ Supabase.</p><p>Các thông tin bạn chọn hiển thị trên hồ sơ và nội dung Discussion có thể được người khác xem theo quyền truy cập của tính năng. Chỉ đưa lên hồ sơ những thông tin bạn muốn chia sẻ.</p><Link href="/settings#account">Quản lý tài khoản & bảo mật →</Link></section>
    <section className={styles.card}><h2>Kết quả bài test và Statistics</h2><p>Quyền đồng ý chia sẻ Statistics được lưu riêng cho từng kết quả bài test. Phân tích phân bố và đối chiếu chỉ sử dụng kết quả được đồng ý chia sẻ; đồng ý Statistics không có nghĩa toàn bộ hồ sơ hay kết quả được công khai cho người khác. Một số số đếm tổng quan về số người và lượt làm bài có thể vẫn được tổng hợp.</p><p>Bạn có thể thu hồi chia sẻ Statistics cho từng kết quả tại hồ sơ. Việc chọn personality identity để hiển thị không tự thay đổi quyền chia sẻ Statistics.</p><Link href="/profile">Xem kết quả và quyền chia sẻ →</Link></section>
    <section className={styles.card}><h2>Nội dung thảo luận và kiểm duyệt</h2><p>Bài viết, bình luận và tệp đính kèm được xử lý để kiểm duyệt trước khi công khai. Hệ thống có thể gửi nội dung cần đánh giá tới Groq, đồng thời lưu kết quả kiểm duyệt và bản chụp nội dung phục vụ quy trình xem xét. Bài trong nhóm riêng tư tuân theo quyền truy cập nhóm.</p><p>Không đưa thông tin bí mật hoặc dữ liệu cá nhân của người khác vào nội dung hay tệp đính kèm.</p></section>
    <section className={styles.card}><h2>Lựa chọn của bạn</h2><p>Settings cho phép chọn loại thông báo mới và cách hiển thị. Bạn cũng có thể quản lý danh sách chặn. Các lựa chọn này không tự xóa nội dung đã đăng hay dữ liệu tài khoản.</p><div className={styles.actions}><Link href="/settings">Mở cài đặt →</Link><Link href="/profile/blocked">Danh sách đã chặn →</Link></div></section>
    <section className={styles.card}><h2>Góp ý và liên hệ</h2><p>Form góp ý chuẩn bị nội dung email trong trình duyệt, không tự gửi hay lưu góp ý vào database của website. Khi bạn gửi bằng ứng dụng email, nội dung và địa chỉ gửi được chuyển tới hộp thư liên hệ MOSAIC. Góp ý đăng trong forum Meta là nội dung Discussion công khai sau khi duyệt.</p><Link href="/contact">Xem các kênh liên hệ →</Link></section>
    <p className={styles.note}><Link href="/feedback">Góp ý về quyền riêng tư</Link> · <Link href="/terms">Điều khoản sử dụng</Link></p></div>;
}
