"use client";
import {useState} from 'react';import Link from 'next/link';
import WorldMap from '@/src/components/statistics/WorldMap';
import countries from '@/lib/statistics/world-countries.json';
import {MBTI_COLORS,ENNEAGRAM_COLORS,type CountryTotals} from '@/lib/statistics/community-map';
import styles from './HomeAtlas.module.css';
export default function HomeAtlasClient({data,available}:{data:CountryTotals[];available:boolean}){
 const [variable,setVariable]=useState<'mbti'|'enneagram'>('mbti');const [selected,setSelected]=useState('VNM');const values=data.find(c=>c.code===selected)?.[variable]||{};const total=Object.values(values).reduce((a,b)=>a+b,0);const colors=variable==='mbti'?MBTI_COLORS:ENNEAGRAM_COLORS;const worldTotal=data.reduce((sum,c)=>sum+Object.values(c[variable]).reduce((a,b)=>a+b,0),0);const countryTotal=data.filter(c=>Object.values(c[variable]).some(n=>n>0)).length;
 return <section className={styles.atlas} aria-labelledby="home-atlas-title"><header><div><small>COMMUNITY ATLAS</small><h2 id="home-atlas-title">Những mảnh ghép trên thế giới</h2><p>Di chuột hoặc chạm vào quốc gia để khám phá phân bố kiểu.</p></div><label className={styles.switch}>Biến thống kê<select value={variable} onChange={e=>setVariable(e.target.value as 'mbti'|'enneagram')}><option value="mbti">MBTI</option><option value="enneagram">Enneagram</option></select></label></header>
 {!available&&<p role="alert">Chưa tải được số liệu. Vui lòng thử lại sau.</p>}<div className={styles.layout}><div className={styles.map}><WorldMap compact data={data} variable={variable} selected={selected} onSelect={setSelected}/><p className={styles.caption}>Màu theo kiểu có nhiều chia sẻ nhất · Kẻ sọc: đồng hạng · Màu trung tính: chưa có dữ liệu.</p></div><aside className={styles.stats}><div className={styles.totals}><div><strong>{available?worldTotal:'—'}</strong><span>chia sẻ {variable==='mbti'?'MBTI':'Enneagram'}</span></div><div><strong>{available?countryTotal:'—'}</strong><span>quốc gia có dữ liệu</span></div></div><label className={styles.countryLabel}>Đang khám phá<select value={selected} onChange={e=>setSelected(e.target.value)}>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><p className={styles.count}>{available?total:'—'} chia sẻ trong quốc gia này</p><div className={styles.distribution}>{total?Object.entries(values).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([t,n])=><div className={styles.row} key={t}><span><i style={{background:colors[t]}}/>{variable==='mbti'?t:'Type '+t}</span><strong>{(n/total*100).toFixed(1)}%</strong><div><b style={{width:`${n/total*100}%`,background:colors[t]}}/></div></div>):<p>{available?'Quốc gia này chưa có chia sẻ. Bạn có thể đóng góp mảnh ghép đầu tiên.':'Chưa có số liệu để hiển thị.'}</p>}</div></aside></div><footer><span>Dữ liệu tự nguyện từ cộng đồng MOSAIC · Nền bản đồ Natural Earth</span><Link href="/statistics/map">Xem đầy đủ & chia sẻ →</Link></footer></section>;
}
