import Link from 'next/link';
import { contactEmail } from '@/lib/contact/message';
import styles from '@/app/home.module.css';
const columns=[
  {title:'Khám phá',links:[['Bài trắc nghiệm','/test'],['Khám phá & kết nối','/discover'],['Thống kê cộng đồng','/statistics'],['Triển lãm nghệ thuật','/about/exhibition']]},
  {title:'Thư viện & cộng đồng',links:[['16 kiểu MBTI','/knowledge/mbti/overview'],['Enneagram','/knowledge/enneagram/overview'],['Cognitive Functions','/knowledge/cognitive/overview'],['System Forums','/discussion'],['Nhóm thảo luận','/discussion/groups']]},
  {title:'MOSAIC & hỗ trợ',links:[['Giới thiệu dự án','/about'],['Nhà phát triển','/about/developer'],['Cập nhật tính năng','/about/news'],['Góp ý','/feedback'],['Liên hệ','/contact'],['Báo lỗi','/support#report']]},
];
export default function HomeFooter(){return <footer className={styles.expandedFooter}><div className={styles.footerTop}><div className={styles.footerBrand}><Link href="/" aria-label="MOSAIC — Trang chủ">MOSAIC</Link><p>Personality in pieces.</p><p>Một không gian khám phá tính cách, đọc sâu về typology và kết nối qua những cuộc thảo luận có ý nghĩa.</p><a className={styles.footerEmail} href={`mailto:${contactEmail}`}>{contactEmail}</a></div>{columns.map(column=><nav key={column.title} aria-label={column.title} className={styles.footerColumn}><h2>{column.title}</h2>{column.links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav>)}</div><div className={styles.footerBottom}><p>© 2026 MOSAIC · Dự án học tập và khám phá bản thân</p><nav aria-label="Chính sách và tài khoản"><Link href="/privacy">Quyền riêng tư</Link><Link href="/terms">Điều khoản</Link><Link href="/settings">Cài đặt</Link></nav><p className={styles.footerDisclaimer}>Nội dung và kết quả trắc nghiệm phục vụ tham khảo, không phải chẩn đoán tâm lý hoặc đánh giá giá trị của một người.</p></div></footer>;}
