'use client';
import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import {getUserProfile,updateUserProfile,type UserProfileData} from '@/app/actions/profile';
import {PRIVATE_FIELDS,birthFacts,type VisibilitySettings,type ProfileField} from '@/lib/profile-policy';
import {notifyAvatarUpdated} from '@/lib/avatar-events';
interface Props {isOpen:boolean;onClose:()=>void;initialData?:{dateOfBirth?:string|Date|null;zodiacSign?:string|null;hobbies?:string|null;location?:string|null;bio?:string|null;avatarUrl?:string|null};onSuccess?:(p:UserProfileData)=>void;title?:string;description?:string;showSkipButton?:boolean;onSkip?:()=>void;}
const labels:Record<ProfileField,string>={username:'Username',displayName:'Tên hiển thị',avatarUrl:'Ảnh đại diện',dateOfBirth:'Ngày sinh',bio:'Giới thiệu',hobbies:'Sở thích',location:'Quốc gia / thành phố'};
export const inputClass='mt-2 w-full rounded-xl border border-[#E2D4B7] bg-[#FAF8F5] p-3 text-[#5C4326]';
export default function ProfileFormModal({isOpen,onClose,onSuccess,title='Chỉnh sửa hồ sơ cá nhân'}:Props){
 const [profile,setProfile]=useState<UserProfileData|null>(null),[visibility,setVisibility]=useState<VisibilitySettings|null>(null),[pending,setPending]=useState(false),[error,setError]=useState('');
 const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!isOpen)return;let active=true;setProfile(null);setError('');getUserProfile().then(r=>{if(active){if(r.success&&r.profile){setProfile(r.profile);setVisibility(r.profile.visibility);}else setError(r.error||'Chưa tải được hồ sơ.');}}).catch(()=>{if(active)setError('Chưa tải được hồ sơ.');});return()=>{active=false;};},[isOpen]);
 useEffect(()=>{if(!isOpen)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape'&&!pending)onClose();if(e.key==='Tab'){const elements=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[isOpen,onClose,pending]);
 if(!isOpen||typeof document==='undefined')return null;
 async function save(form:FormData){setPending(true);setError('');try{const result=await updateUserProfile({username:String(form.get('username')),displayName:String(form.get('displayName')),dateOfBirth:String(form.get('dateOfBirth'))||null,bio:String(form.get('bio')),location:String(form.get('location')),hobbies:String(form.get('hobbies')),visibility:visibility||undefined});if(!result.success){setError(result.error||'Chưa lưu được.');return;}if(result.profile)onSuccess?.(result.profile);onClose();}catch{setError('Chưa kết nối được. Vui lòng thử lại.');}finally{setPending(false);}}
 async function upload(file:File|undefined){if(!file)return;setPending(true);setError('');try{const body=new FormData();body.set('avatar',file);const response=await fetch('/api/profile/avatar',{method:'POST',body});const r=await response.json();if(!response.ok)throw Error(r.error);setProfile(p=>p?{...p,avatarUrl:r.avatarUrl}:p);notifyAvatarUpdated(r.avatarUrl);}catch(e){setError(e instanceof Error?e.message:'Chưa tải được ảnh.');}finally{setPending(false);}}
 return createPortal(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-3"><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="profile-editor-title" className="max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-2xl border border-[#E2D4B7] bg-[#FCFBF8] p-5 sm:p-8"><h2 id="profile-editor-title" className="font-serif text-2xl text-[#5C4326]">{title}</h2><p className="mt-2 text-sm">Tuổi và cung hoàng đạo tự tính từ ngày sinh. Typology đã điền luôn công khai.</p>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{!profile?<p>Đang tải hồ sơ…</p>:<form action={save}><fieldset disabled={pending} className="space-y-5 mt-5">{PRIVATE_FIELDS.map(field=><div key={field}><label className="block" htmlFor={`edit-${field}`}>{labels[field]}</label>{field==='avatarUrl'?<div>{profile.avatarUrl&&<img src={profile.avatarUrl} alt="Ảnh đại diện của bạn" className="my-2 h-16 w-16 rounded-full object-cover"/>}<input id={`edit-${field}`} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>void upload(e.target.files?.[0])}/><button type="button" className="ml-3" onClick={async()=>{setPending(true);try{const r=await updateUserProfile({avatarUrl:null});if(r.success&&r.profile){setProfile(r.profile);notifyAvatarUpdated(null);}else setError(r.error||'Chưa gỡ được ảnh.');}finally{setPending(false);}}}>Gỡ ảnh</button></div>:field==='bio'||field==='hobbies'?<textarea id={`edit-${field}`} name={field} defaultValue={profile[field]||''} maxLength={field==='bio'?2000:1000} className={inputClass}/>:<input id={`edit-${field}`} name={field} type={field==='dateOfBirth'?'date':'text'} required={field==='username'||field==='displayName'} defaultValue={field==='dateOfBirth'?profile.dateOfBirth?new Date(profile.dateOfBirth).toISOString().slice(0,10):'':profile[field]||''} maxLength={field==='username'?30:field==='displayName'?80:160} className={inputClass}/>}<label className="mt-2 flex items-center justify-between text-sm">Ai có thể xem {labels[field].toLowerCase()}?<select aria-label={`Quyền xem ${labels[field]}`} value={visibility?.[field]} onChange={e=>setVisibility(v=>v?{...v,[field]:e.target.value}:v)} className="rounded border border-[#E2D4B7] p-2"><option value="PUBLIC">Công khai</option><option value="FRIENDS">Bạn bè</option><option value="PRIVATE">Riêng tư</option></select></label></div>)}<p>{profile.age!==null?`${birthFacts(profile.dateOfBirth).age} tuổi · ${birthFacts(profile.dateOfBirth).zodiacSign}`:''}</p><div className="flex justify-end gap-3"><button type="button" onClick={onClose}>Hủy</button><button className="rounded-xl bg-[#8B6B4A] px-5 py-3 text-white" type="submit">{pending?'Đang lưu…':'Lưu thay đổi'}</button></div></fieldset></form>}<button type="button" disabled={pending} onClick={onClose} className="mt-4">Đóng</button></div></div>,document.body);
}
