"use client";
import WorldMap from './WorldMap';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@clerk/nextjs';
import Link from 'next/link';
import countries from '@/lib/statistics/world-countries.json';
import { MBTI_COLORS, ENNEAGRAM_COLORS, leadingTypes, type CountryTotals } from '@/lib/statistics/community-map';
import { saveMapShare, withdrawMapShare } from '@/app/actions/community-map';
import styles from './CommunityMap.module.css';
type Share = {countryCode:string;mbti:string|null;enneagram:string|null} | null;
export default function CommunityMap({data,available,initialShare}:{data:CountryTotals[];available:boolean;initialShare:Share}) {
 const [variable,setVariable]=useState<'mbti'|'enneagram'>('mbti'); const [filter,setFilter]=useState(''); const [selected,setSelected]=useState('VNM'); const [zoom,setZoom]=useState(1);
 const [country,setCountry]=useState(initialShare?.countryCode||'');const [mbti,setMbti]=useState(initialShare?.mbti||'');const [enneagram,setEnneagram]=useState(initialShare?.enneagram||'');const [consent,setConsent]=useState(false);const [message,setMessage]=useState(''); const [pending,start]=useTransition(); const {isSignedIn}=useUser();const router=useRouter();
 const colors=variable==='mbti'?MBTI_COLORS:ENNEAGRAM_COLORS;
 const lookup=new Map(data.map(c=>[c.code,c]));const values=lookup.get(selected)?.[variable]||{};const total=Object.values(values).reduce((a,b)=>a+b,0);
 return <div className={styles.page}>
  <header className={styles.header}><Link href="/statistics">Statistics / Bản đồ cộng đồng</Link><h1>MOSAIC trên bản đồ thế giới</h1><p>Những mảnh ghép MBTI và Enneagram được cộng đồng tự nguyện chia sẻ theo quốc gia.</p></header>
  <div className={styles.controls}><label>Biến thống kê<select value={variable} onChange={e=>{setVariable(e.target.value as 'mbti'|'enneagram');setFilter('');}}><option value="mbti">MBTI</option><option value="enneagram">Enneagram</option></select></label><label>Kiểu hiển thị<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Kiểu có nhiều chia sẻ nhất</option>{Object.keys(colors).map(t=><option key={t} value={t}>{variable==='mbti'?t:'Type '+t}</option>)}</select></label><label>Chọn quốc gia<select value={selected} onChange={e=>setSelected(e.target.value)}>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label></div>
  {!available&&<p role="alert">Chưa tải được dữ liệu bản đồ. Vui lòng thử lại sau.</p>}
  <div className={styles.layout}><section className={styles.mapPanel} aria-label="Bản đồ thế giới"><div className={styles.zoom}><button type="button" aria-label="Thu nhỏ bản đồ" onClick={()=>setZoom(z=>Math.max(1,z-.5))}>−</button><span>{zoom}×</span><button type="button" aria-label="Phóng to bản đồ" onClick={()=>setZoom(z=>Math.min(3,z+.5))}>+</button></div><WorldMap data={data} variable={variable} filter={filter} selected={selected} onSelect={setSelected} zoom={zoom}/><p className={styles.caption}>{filter?'Màu đánh dấu quốc gia có chia sẻ kiểu đã chọn.':'Màu biểu thị kiểu có nhiều chia sẻ nhất trong mỗi quốc gia; kẻ sọc biểu thị đồng hạng.'} Màu trung tính: chưa có dữ liệu. Đây là mẫu tự nguyện của MOSAIC.</p><p className={styles.source}>Nền bản đồ: Natural Earth, tỷ lệ 1:110m. Bản đồ không thể hiện quan điểm về biên giới.</p></section>
  <aside className={styles.country}><small>HỒ SƠ QUỐC GIA</small><h2>{countries.find(c=>c.code===selected)?.name}</h2><p>{total} chia sẻ {variable==='mbti'?'MBTI':'Enneagram'}</p>{total?Object.entries(values).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([t,n])=><div className={styles.row} key={t}><span><i style={{background:colors[t]}}/>{variable==='mbti'?t:'Type '+t}</span><span>{n} · {(n/total*100).toFixed(1)}%</span><div className={styles.track}><div style={{width:`${n/total*100}%`,background:colors[t]}}/></div></div>):<p>Chưa có chia sẻ cho quốc gia này.</p>}</aside></div>
  <div className={styles.legend}>{Object.entries(colors).map(([t,c])=><button type="button" key={t} aria-pressed={filter===t} onClick={()=>setFilter(f=>f===t?'':t)}><i style={{background:c}}/>{variable==='mbti'?t:'Type '+t}</button>)}</div>
  <section className={styles.share}><h2>Thêm mảnh ghép của bạn</h2><p>Chọn quốc gia và kiểu bạn muốn đóng góp. Bạn có thể cập nhật hoặc rút chia sẻ bất cứ lúc nào.</p>{isSignedIn?<form onSubmit={e=>{e.preventDefault();start(async()=>{const result=await saveMapShare({countryCode:country,mbti,enneagram,consent});setMessage(result.message);if(result.success){setConsent(false);router.refresh();}});}}><div className={styles.controls}><label>Quốc gia<select required value={country} onChange={e=>setCountry(e.target.value)}><option value="">Chọn quốc gia</option>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label>MBTI<select value={mbti} onChange={e=>setMbti(e.target.value)}><option value="">Không chia sẻ</option>{Object.keys(MBTI_COLORS).map(t=><option key={t}>{t}</option>)}</select></label><label>Enneagram<select value={enneagram} onChange={e=>setEnneagram(e.target.value)}><option value="">Không chia sẻ</option>{Object.keys(ENNEAGRAM_COLORS).map(t=><option key={t} value={t}>Type {t}</option>)}</select></label></div><label className={styles.consent}><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Tôi đồng ý dùng quốc gia và kiểu đã chọn cho thống kê tổng hợp công khai; tên và tài khoản của tôi không hiển thị trên bản đồ.</label><button disabled={pending} type="submit">{pending?'Đang lưu…':'Lưu chia sẻ'}</button>{initialShare&&<button disabled={pending} type="button" onClick={()=>start(async()=>{const result=await withdrawMapShare();setMessage(result.message);if(result.success)router.refresh();})}>Rút chia sẻ</button>}<p role="status">{message}</p></form>:<Link href="/sign-in?redirect_url=%2Fstatistics%2Fmap">Đăng nhập để chia sẻ →</Link>}</section>
 </div>;
}
